version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: job_agregator_db
    restart: always
    environment:
      POSTGRES_USER: admin     # Логин
      POSTGRES_PASSWORD: root  # Пароль (для локальной разработки простые ок)
      POSTGRES_DB: job_agregator_db # Имя базы, создастся автоматически
    ports:
      - "5444:5432"            # Прокидываем порт наружу, чтобы IDEA могла подключиться
    volumes:
      - db_data:/var/lib/postgresql/data # Чтобы данные не терялись при перезапуске контейнера

volumes:
  db_data: